"$schema" = 'https://starship.rs/config-schema.json'

# Philosophy: "Focus" Theme. Monochromatic with a single accent for Git.
# This creates a very clean, professional, and distraction-free look.
format = """
[](surface0)\
$os\
$username\
[](bg:surface1 fg:surface0)\
$directory\
[](bg:teal fg:surface1)\
$git_branch\
$git_status\
[](fg:teal bg:surface1)\
$python\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
[](fg:surface1 bg:surface2)\
$conda\
$time\
[ ](fg:surface2)\
$cmd_duration\
$line_break\
$character"""

palette = 'ayu_dark'

[os]
disabled = false
style = "bg:surface0 fg:text"
format = '[$symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "bg:surface1 fg:text" # Using the same base color for a seamless look
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# The "Focus" color. Teal is a great choice as it's calm and professional.
[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:teal)]($style)'

# Language indicators are subtle, using the same background as the directory.
[python]
disabled = true
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[nodejs]
disabled = true
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[c]
symbol = " "
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[rust]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[golang]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[php]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[java]
symbol = " "
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[kotlin]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[haskell]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[lua]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol ($version) ](fg:subtext1 bg:surface1)]($style)'

[docker_context]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol $context ](fg:subtext1 bg:surface1)]($style)'

[package]
symbol = "󰏗"
style = "bg:surface1"
format = '[[ $symbol $version ](fg:subtext1 bg:surface1)]($style)'

# (Apply the same "bg:surface1" and "fg:subtext1" style to other language modules: rust, golang, etc.)
# ...

[conda]
symbol = "  "
style = "bg:surface2 fg:text"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:surface2"
format = '[[  $time ](fg:subtext1 bg:surface2)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold teal)' # Use the accent color for success
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_replace_one_symbol = '[❮](bold lavender)'
vimcmd_replace_symbol = '[❮](bold lavender)'
vimcmd_visual_symbol = '[❮](bold yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:overlay0"
disabled = false

# --- PALETTES (No change needed) ---
[palettes.ayu_dark]
rosewater = "#F29E74"
flamingo = "#FF8F40"
pink = "#D2A6FF"
mauve = "#D2A6FF"
red = "#F51818"
maroon = "#E65050"
peach = "#FF8F40"
yellow = "#FFB454"
green = "#AAD94C"
teal = "#4CBF99"
sky = "#59C2FF"
sapphire = "#59C2FF"
blue = "#39BAE6"
lavender = "#D2A6FF"
text = "#E6E1CF"
subtext1 = "#C7C7C7"
subtext0 = "#ACAFB4"
overlay2 = "#828C99"
overlay1 = "#6C7986"
overlay0 = "#5C6773"
surface2 = "#343A46"
surface1 = "#272D38"
surface0 = "#1F2430"
base = "#0A0E14"
mantle = "#0D1017"
crust = "#06080A"
# ... other palettes
